print("hiiiiiiiiiiiiiiiiiiiiiiii")
print("helloooooooooooooooooo")
print("newwwwwwwwwwwwwwwwwwwwwwww")
print("gooooooooooooooooooooo")
print("hiiiiiiiiiiiiiiiiiiiiiiii mjfdtfgh")
print("helloooooooooooooooooo qwerty")
print("newwwwwwwwwwwwwwwwwwwwwwww asdfg")
print("gooooooooooooooooooooo zxcv")
